### ISSUE TITLE
crash on zshall(1)

### ISSUE THREAD

**Issue by nl6720** [lahwaacz/archweb_manpages#2]
http://jlk.fjfi.cvut.cz/arch/manpages/man/extra/zsh/zshall.1.en

```
500 — Internal server error
The web application crashed.
```

**Comment by lahwaacz** [comment]
That's because the [source](http://jlk.fjfi.cvut.cz/arch/manpages/man/extra/zsh/zshall.1.en.raw) contains multiple [.so macros](http://jlk.fjfi.cvut.cz/arch/manpages/dev#.so_macros) which should include the content of other pages:

```
.so man1/zshroadmap.1
.so man1/zshmisc.1
.so man1/zshexpn.1
.so man1/zshparam.1
.so man1/zshoptions.1
.so man1/zshbuiltins.1
.so man1/zshzle.1
.so man1/zshcompwid.1
.so man1/zshcompsys.1
.so man1/zshcompctl.1
.so man1/zshmodules.1
.so man1/zshcalsys.1
.so man1/zshtcpsys.1
.so man1/zshzftpsys.1
.so man1/zshcontrib.1
```
Since everything is in an SQL database instead of a file system, the converter cannot access them... We could either try to replace the `.so` macros manually (it's already done if there is nothing else on the page) or render an incomplete version.

**Comment by nl6720** [comment]
You mean all pages under http://jlk.fjfi.cvut.cz/arch/manpages/dev#.so_macros are fixed manually?
I presumed that since they all work, the .so macro functionality is working.

**Comment by lahwaacz** [comment]
I'm just checking if the page contains only one `.so` macro and no text, in which case I simply render the referenced page. The `zshall(1)` page would need a full preprocessor, i.e. recursive in-text replacement with protection against infinite recursion, and the database would have to be adjusted so that the HTML cache is properly invalidated whenever an included page changes.

**Comment by lahwaacz** [comment]
I've tried to implement the recursive preprocessor, so [zshall(1)](http://jlk.fjfi.cvut.cz/arch/manpages/man/extra/zsh/zshall.1.en) does not crash anymore. Could you please check that it contains the same text as the console version?

This also revealed a bug in mandoc, which generates duplicate anchors for recurrent chapters such as "NAME" or "DESCRIPTION". I've sent a message to its developer.

There is still at least one message which crashes due to the .so macro: [cmake-properties(7)](http://jlk.fjfi.cvut.cz/arch/manpages/man/extra/cmake/cmake-properties.7.en). This is due to regular text
```
Set the Android property that specifies directories to search for the
.so libraries.
```
which is interpreted as a reference to some `libraries` file.

And I should still write the cache invalidation code...

**Comment by nl6720** [comment]
In a quick skim through it, I found only one issue:
zshall(1) in `man` has page names before the each included page:

```
...
       Any  of  these  files may be pre-compiled with the zcompile builtin command (see zshbuiltins(1)).  If a compiled file exists (named for the original file
       plus the .zwc extension) and it is newer than the original file, the compiled file will be used instead.

ZSHROADMAP(1)                                                        General Commands Manual                                                       ZSHROADMAP(1)

NAME
       zshroadmap - informal introduction to the zsh manual The Zsh Manual, like the shell itself, is large and often complicated.  This section of  the  manual
       provides some pointers to areas of the shell that are likely to be of particular interest to new users, and indicates where in the rest of the manual the
       documentation is to be found.
...
```

http://jlk.fjfi.cvut.cz/arch/manpages/man/extra/zsh/zshall.1.en doesn't have that.

**Comment by lahwaacz** [comment]
Hmm, indeed - though I'd be inclined to believe that this is a feature :wink:

**Comment by nl6720** [comment]
The NAME section looks a little out of place without it, but ... it's not really that important for me.

**Comment by lahwaacz** [comment]
Actually, the opinion of the mandoc developer is that pages including multiple other pages are an abuse of the system, they should use proper "See also" sections instead. We should probably let the zsh devs know about this so they can rewrite the page. That also answers the question whether the missing page names are a bug or a feature.

It also seems that `zshall(1)` is the only page in the database doing such things, so I'm not going to deal with general invalidation of the HTML cache. As long as only pages from the same package are included, it will be invalidated implicitly though.
