### ISSUE TITLE
Links of cross-references are broken

### ISSUE THREAD

**Issue by wlhlm** [lahwaacz/archweb_manpages#8]
Cross-reference HTML links are broken since they are missing a `/`.

An [example manpage](https://jlk.fjfi.cvut.cz/arch/manpages/man/pam_env.8) references `pam(8)` in the `SEE ALSO`-section, but the link is 
```
https://jlk.fjfi.cvut.cz/arch/manpagesman/pam.8.en
```
rather than
```
https://jlk.fjfi.cvut.cz/arch/manpages/man/pam.8.en
```

This is probably fixed by adding the `/` on the following line (sorry for being too lazy to open a pull request):
https://github.com/lahwaacz/archweb_manpages/blob/9d688820b0a7d78291c769fb71e91d3ffd57a834/archweb_manpages/utils.py#L81-L83

**Comment by lahwaacz** [comment]
Nope, it was caused by a configuration problem originating from a migration to Django 2.1, so for some time the URLs containing `/manpagesman/` were accepted and it just happened that the cache still had an old version of this page. I run the `drop_cache.py` script now, so everything should be fine.

In any case, thanks for the report!
